"""
Dashboard generator for the E-commerce Big Data project.

Creates output/dashboard.html from the CSV results and PNG plots generated by
run_project.py. It uses only Python + pandas, so no extra dashboard framework
or server is required. Open the generated HTML file in a browser.
"""

import html
import os
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "output"
RESULTS = OUTPUT / "results"
PLOTS = OUTPUT / "plots"
DASHBOARD = OUTPUT / "dashboard.html"


def read_csv(name, default=None):
    path = RESULTS / name
    if not path.exists():
        return default if default is not None else pd.DataFrame()
    return pd.read_csv(path)


def money(value):
    try:
        return f"£{float(value):,.2f}"
    except Exception:
        return "-"


def number(value):
    try:
        return f"{float(value):,.0f}"
    except Exception:
        return "-"


def table_html(df, max_rows=10):
    if df is None or df.empty:
        return '<div class="empty">No data available.</div>'
    show = df.head(max_rows).copy()
    return show.to_html(index=False, classes="data-table", border=0, escape=True)


def plot_card(filename, title, description):
    path = PLOTS / filename
    if not path.exists():
        return ""
    return f"""
    <div class="chart-card">
      <h3>{html.escape(title)}</h3>
      <p>{html.escape(description)}</p>
      <img src="plots/{html.escape(filename)}" alt="{html.escape(title)}">
    </div>
    """


def build_dashboard():
    summary = read_csv("behaviour__summary.csv")
    top_products = read_csv("products__top_products_by_revenue.csv")
    top_qty = read_csv("products__top_products_by_qty.csv")
    monthly = read_csv("patterns__monthly_trend.csv")
    countries = read_csv("patterns__country_revenue.csv")
    segments = read_csv("segmentation__cluster_profile.csv")
    recommendations = next(iter(sorted(RESULTS.glob("recommendations__customer_*.csv"))), None)
    rec_df = pd.read_csv(recommendations) if recommendations else pd.DataFrame()

    if summary.empty:
        raise FileNotFoundError(
            "Dashboard data is missing. Run `python run_project.py` first."
        )

    row = summary.iloc[0]
    total_customers = number(row.get("total_customers"))
    total_transactions = number(row.get("total_transactions"))
    total_revenue = money(row.get("total_revenue"))
    avg_order = money(row.get("avg_order_value"))

    segment_rows = ""
    if not segments.empty:
        for _, r in segments.iterrows():
            label = html.escape(str(r.get("segment_label", "Segment")))
            count = number(r.get("num_customers"))
            segment_rows += f"<div class='segment'><span>{label}</span><strong>{count}</strong></div>"

    rec_title = "Sample recommendations"
    if recommendations:
        customer_text = recommendations.stem.replace("recommendations__customer_", "Customer ")
        rec_title = f"Recommendations — {html.escape(customer_text)}"

    html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>E-Commerce Big Data Analytics Dashboard</title>
<style>
  * {{ box-sizing: border-box; }}
  body {{ margin:0; font-family:Segoe UI, Arial, sans-serif; background:#f4f7fb; color:#172033; }}
  .hero {{ background:linear-gradient(135deg,#172554,#2563eb); color:white; padding:34px 6%; }}
  .hero h1 {{ margin:0 0 8px; font-size:32px; }}
  .hero p {{ margin:0; opacity:.9; font-size:15px; }}
  .wrap {{ width:88%; max-width:1250px; margin:26px auto 50px; }}
  .cards {{ display:grid; grid-template-columns:repeat(4,1fr); gap:16px; margin-bottom:24px; }}
  .card {{ background:white; border-radius:14px; padding:20px; box-shadow:0 5px 20px rgba(20,35,70,.08); }}
  .label {{ color:#64748b; font-size:13px; }}
  .value {{ font-size:25px; font-weight:700; margin-top:7px; }}
  .section {{ margin-top:28px; }}
  .section h2 {{ margin-bottom:14px; }}
  .grid {{ display:grid; grid-template-columns:1fr 1fr; gap:18px; }}
  .chart-card {{ background:white; border-radius:14px; padding:18px; box-shadow:0 5px 20px rgba(20,35,70,.08); }}
  .chart-card h3 {{ margin:0 0 5px; }}
  .chart-card p {{ color:#64748b; margin:0 0 14px; font-size:13px; }}
  .chart-card img {{ width:100%; border-radius:8px; background:#fff; }}
  .table-card {{ background:white; border-radius:14px; padding:18px; overflow:auto; box-shadow:0 5px 20px rgba(20,35,70,.08); }}
  .data-table {{ border-collapse:collapse; width:100%; font-size:13px; }}
  .data-table th, .data-table td {{ padding:9px 10px; border-bottom:1px solid #e5e7eb; text-align:left; }}
  .data-table th {{ background:#f8fafc; }}
  .segments {{ display:grid; grid-template-columns:repeat(4,1fr); gap:12px; }}
  .segment {{ background:white; padding:16px; border-radius:12px; box-shadow:0 4px 15px rgba(20,35,70,.06); }}
  .segment span {{ display:block; color:#64748b; font-size:13px; }}
  .segment strong {{ display:block; margin-top:7px; font-size:23px; }}
  .empty {{ color:#64748b; padding:15px 0; }}
  footer {{ color:#64748b; text-align:center; padding:20px; font-size:12px; }}
  @media(max-width:900px) {{ .cards,.segments {{grid-template-columns:1fr 1fr}} .grid {{grid-template-columns:1fr}} }}
  @media(max-width:560px) {{ .cards,.segments {{grid-template-columns:1fr}} .wrap {{width:94%}} }}
</style>
</head>
<body>
<header class="hero">
  <h1>E-Commerce Big Data Analytics Dashboard</h1>
  <p>PySpark • Customer Behaviour • RFM + K-Means • ALS Recommendations</p>
</header>
<main class="wrap">
  <section class="cards">
    <div class="card"><div class="label">Total Customers</div><div class="value">{total_customers}</div></div>
    <div class="card"><div class="label">Transactions</div><div class="value">{total_transactions}</div></div>
    <div class="card"><div class="label">Total Revenue</div><div class="value">{total_revenue}</div></div>
    <div class="card"><div class="label">Average Order Value</div><div class="value">{avg_order}</div></div>
  </section>

  <section class="section">
    <h2>Customer Segmentation</h2>
    <div class="segments">{segment_rows}</div>
  </section>

  <section class="section grid">
    {plot_card('01_top_products_by_revenue.png', 'Top Products by Revenue', 'Products contributing the most revenue.')}
    {plot_card('02_revenue_by_country.png', 'Revenue by Country', 'Top countries by recorded revenue.')}
    {plot_card('03_customer_spending_distribution.png', 'Customer Spending Distribution', 'Distribution of customer spending.')}
    {plot_card('04_monthly_revenue_trend.png', 'Monthly Revenue Trend', 'Revenue pattern across months.')}
    {plot_card('05_customer_segment_distribution.png', 'Customer Segment Distribution', 'Distribution of customers across K-Means segments.')}
    {plot_card('06_sample_recommendations.png', 'Sample Recommendations', 'Products recommended by the ALS model.')}
  </section>

  <section class="section grid">
    <div class="table-card"><h2>Top Products by Revenue</h2>{table_html(top_products)}</div>
    <div class="table-card"><h2>Top Products by Quantity</h2>{table_html(top_qty)}</div>
    <div class="table-card"><h2>Monthly Revenue</h2>{table_html(monthly)}</div>
    <div class="table-card"><h2>Revenue by Country</h2>{table_html(countries)}</div>
    <div class="table-card"><h2>{rec_title}</h2>{table_html(rec_df, 5)}</div>
  </section>
</main>
<footer>Generated from the project's actual output/results and output/plots files.</footer>
</body>
</html>
"""

    DASHBOARD.write_text(html_doc, encoding="utf-8")
    print(f"[dashboard] Saved {DASHBOARD}")


if __name__ == "__main__":
    build_dashboard()
